### ISSUE TITLE
Issues using the '|=|' In operator with local lists.

### ISSUE THREAD

**Issue by nicholas-peterson** [fsprojects/DynamicsCRMProvider#15]
### Description

I know this isn't an actively developed type provider, but one thing I ran into awhile back bugged me and thought I'd ask. I was trying to issue a query using a where clause with the |=| operator against a list of strings. Imagine ' (where entitySet.email |=| listOfStrings)'. The listOfStrings value here would be local (it came from a List.chunkBySize operation. It compiles fine but when it runs it yells about how ConditionOperator.Like expects a single value not a seq. But checking the code, 'Like' uses a different operator. Is there something odd I have to do in the query expression to use an F# list of strings correctly? I've tried using an Array of string as well, but that also fails.

This is running on .net 4.6 in  windows against crm 2011.

**Comment by sergey-tihon** [comment]
Is  `|=|` your custom operator?

**Comment by nicholas-peterson** [comment]
It's in this project, the code appears to map it to the CRM query expression condition operator "In" and then it boxes the value which is of type seq. What's odd, if I put a literal list in the f# query expression this operator works as expected. But if I put a variable of type list/seq/array in the same spot it fails.

**Comment by pezipink** [comment]
When I first wrote this many years ago, that operator was only designed to work with inline arrays.  If you replace the NewArrayValues pattern with the SeqValues pattern from the SqlProvider project, it should work with any sequence.
