### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/DynamicsCRMProvider#2]
There are no required assemblies in `lib` folder.
![image](https://cloud.githubusercontent.com/assets/1197905/6505980/4873ac7c-c358-11e4-95d1-86065dd3794a.png)
@forki @pezipink Could you please commit them?

**Comment by forki** [comment]
I assume this is a license issue. We can't commit that stuff.

**Comment by pezipink** [comment]
Yes I think you are right.

They are just the libraries included as part of the CRM SDK which you can download.  This was built against  SDK Version 5.0.12, it may or may not work with newer versions.... but them CRM guys are notoriously vigilant in maintaining backwards compatibility, even if it means their product goes at a snail's pace :)

**Comment by sergey-tihon** [comment]
I did not find `Microsoft.Crm.Services.Utility.dll` there...

Can we use some of their official `NuGet` packages?
https://www.nuget.org/profiles/crmsdk

**Comment by pezipink** [comment]
possibly, I have no access to an XRM system to help you though.  Thankfully I do not have to use it anymore .

**Comment by sergey-tihon** [comment]
In general, `paket` can download CRM SDK installer from MS site...
But I do not know to extract assemblies from `.exe` without installation)

**Comment by sergey-tihon** [comment]
HA, I know how to fix it )))))
We can't commit these dlls due to license issue, but we pack them into NuGet package.
So I can restore them from there )))

**Comment by forki** [comment]
what's the difference? I we push to nuget we redistribute the dlls.

**Comment by sergey-tihon** [comment]
But they are already on NuGet inside our package.

**Comment by forki** [comment]
I think this is actually a mistake. We should ask for permission or remove these again

**Comment by sergey-tihon** [comment]
@forki Do you know how we can ask?

**Comment by JimDaly** [comment]
You just configure the nuget packages in your project to point to the CRM assemblies on nuget. When the project gets built, it will download the assemblies from nuget. All of the samples within the CRM SDK do this. If you need a specific version you can specify that. See https://msdn.microsoft.com/en-us/library/dn689029.aspx

**Comment by sergey-tihon** [comment]
Thank you @JimDaly ! This is awesome, I found everything except `Microsoft.Crm.Services.Utility.dll`
Does compiled samples are available on NuGet?

**Comment by JimDaly** [comment]
We don’t deliver any compiled samples in the SDK. Just code in projects.
I haven’t heard of Microsoft.Crm.Services.Utility.dll. We don’t ship it but I see it online at https://www.openhub.net/p/fsharp3sample/commits?query=Microsoft.Crm.Services.Utility.dll
We have a CrmSvcUtil.exe which includes the namespace ‘Microsoft.Crm.Services.Utility”  See Create early bound entity classes with the code generation tool (CrmSvcUtil.exe)<https://msdn.microsoft.com/en-us/library/gg327844.aspx>.
When you write your own flavor of CrmSvcUtil.exe, you link to CrmSvcUtil.exe and that provides you the namespace.
So, if someone was making an F# version of entity classes generated by that utility they might produce that – but we don’t ship it.

**Comment by pezipink** [comment]
@sergey-tihon what breaks if you remove the reference?  Maybe it was some utility function, I really can't remember now, it was a long time ago.  We are of not using CrmServiceUtil to generate code, that was what I was avoiding with the erasing type provider :)  The post I wrote originally does not seem to mention that lib.

http://blogs.msdn.com/b/fsharpteam/archive/2013/02/14/the-f-microsoft-dynamics-crm-type-provider-sample-strongly-typed-enterprise-scale-customer-data-made-simple.aspx
